<template>
  <div>
    <Navbar />
    <div>
      <div class="nav-background"></div>
      <div class="header">
        <div class="wrapper">
          <div class="row">
            <div class="col lg-12">
              <h1 class="header-title">Blog</h1>
              <div class="header-description">
                News, stories and tips on project management, collaboration
                &amp; productivity
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section">
        <div class="wrapper">
          <div class="row-2">
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/plant.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">25 Dec 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Jess Edy</p>
                  </div>
                  <h3 class="blog-grid-title">
                    The 31 tools we use to make our “semi remote” SaaS team work
                    efficiently
                  </h3>
                  <p class="paragraph-small">
                    A strong team of people who work well together can only be
                    beneficial to a business
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/boat.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">12 Dec 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Adrian Nilly</p>
                  </div>
                  <h3 class="blog-grid-title">
                    How Envato’s agile UX team works
                  </h3>
                  <p class="paragraph-small">
                    This sounds like an amazing idea, I had a team work on a
                    similar idea for a design class once and we all really liked
                    it! I also love the fact that you’ve taken the initiative to
                    share the idea with a huge audience on Medium, that takes
                    some guts!
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/blue.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal meta-info">
                    <p class="paragraph-small meta-info">25 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Nataliia Peterheria</p>
                  </div>
                  <h3 class="blog-grid-title">
                    Effective tips on how to improve teamwork at workplace
                  </h3>
                  <p class="paragraph-small">
                    Recently, on our Medium blog and via our social media
                    channels, we’ve been communicating quite a bit about some of
                    the specifics surrounding
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/world.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">23 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Barış Karaman</p>
                  </div>
                  <h3 class="blog-grid-title">
                    Extreme Teamwork: Solving the Coordination Problem at 400
                    Miles Per Hour
                  </h3>
                  <p class="paragraph-small">
                    We take the idea of decentralization very seriously in
                    Ethereum. The decentralization is real.
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/plane.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">16 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Kenzo Takahashi</p>
                  </div>
                  <h3 class="blog-grid-title">
                    Let’s get rid of COB deadlines: a better way to manage your
                    team’s workflow
                  </h3>
                  <p class="paragraph-small">
                    Learn how to use the combined shape method in Sketch to
                    create buttons that responds to its override text length.
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/stripe.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">13 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Timothy Frog</p>
                  </div>
                  <h3 class="blog-grid-title">
                    Project Management 3.0 — Why Design Thinking is the Next-Gen
                  </h3>
                  <p class="paragraph-small">
                    The popular design app for Mac is a refined evolution of the
                    “pen-and-paper simulator”, but does not attempt to model
                    user experiences
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/850.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">7 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Oren Ellenbogen</p>
                  </div>
                  <h3 class="blog-grid-title">
                    How we use Slack, Trello and TeamGantt for project
                    management as a digital agency
                  </h3>
                  <p class="paragraph-small">
                    Nesting symbols in Sketch is a dynamic workflow that saves
                    time, creates consistency throughout your designs, and most
                    importantly
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/never-stress.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">2 Nov 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Daniel Pasco</p>
                  </div>
                  <h3 class="blog-grid-title">
                    From Manual Procedures to Machines — The Role of AI and
                    Automation
                  </h3>
                  <p class="paragraph-small">
                    A strong team of people who work well together can only be
                    beneficial to a business
                  </p>
                </div></a
              >
            </div>
            <div class="col-2 lg-4 sm-2">
              <a
                href="single-blog.html"
                class="blog-thumbnail-container no-border w-inline-block"
                ><img src="assets/images/hello.jpg" width="533" alt="" />
                <div class="padding no-horizontal-padding">
                  <div class="flex-horizontal">
                    <p class="paragraph-small meta-info">22 Oct 2019</p>
                    <p class="paragraph-small-2 divider-line">|</p>
                    <p class="paragraph-small meta-info">Bennett Garner</p>
                  </div>
                  <h3 class="blog-grid-title">
                    Writing User Stories, Examples and Templates in Agile
                    Methodologies
                  </h3>
                  <p class="paragraph-small">
                    With the abundance of new tech devices it’s easy to get
                    frustrated and confused about how to properly prepare assets
                    for different devices
                  </p>
                </div></a
              >
            </div>
            <div class="col-2">
              <div class="paging-container">
                <div>
                  <span class="paging-arrow">&lt;</span>
                  <span class="paging-number current">1</span>
                  <span class="paging-number">2</span>
                  <span class="paging-number">3</span>
                  <span class="paging-number">4</span>
                  <span class="paging-number">5</span>
                  <span class="paging-arrow">&gt;</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>
</template>

<script>
// @ is an alias to /src
import Navbar from "@/components/Navbar.vue";
import Footer from "@/components/Footer.vue";

export default {
  name: "Blog",
  components: {
    Navbar,
    Footer,
  },
};
</script>